# The content of this file will be merged with the main config file
# You can add new sections, properties, or override existing ones
# Check printer.generated.cfg to see the generated printer config used in GoKlipper

# You can override a section from the main config file by adding it here
# New properties will be merged and added, and existing ones will override the main config file
# [pause_resume]
# z_up: 11

# You can remove entire sections using a ! before the section name
# [!gcode_macro M486]

# You can also remove specific properties from a section using a ! before the property name
# [pause_resume]
# !z_up:

[gcode_macro TRAM_BED]
description: Probe 3 lead screw positions (3 samples each) to guide manual bed leveling
gcode:
  G28
  SET_HEATER_TEMPERATURE HEATER=heater_bed TARGET=60
  SET_HEATER_TEMPERATURE HEATER=extruder TARGET=140
  M190 S60
  M109 S140
  G1 Z10 F600
  G1 X30 Y30 F6000
  PROBE_ACCURACY SAMPLES=3
  G1 Z10 F600
  G1 X320 Y30 F6000
  PROBE_ACCURACY SAMPLES=3
  G1 Z10 F600
  G1 X175 Y320 F6000
  PROBE_ACCURACY SAMPLES=3
  G1 Z10 F600
  G1 X175 Y175 F6000
